//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAtelier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int idPers { get; set; }
        public Nullable<int> qteF { get; set; }
        public string designationF { get; set; }
        public Nullable<int> prixUnitF { get; set; }
        public Nullable<int> montantF { get; set; }
        public Nullable<System.DateTime> DateHeureF { get; set; }
    }
}
