//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAtelier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gerant
    {
        public int idPers { get; set; }
        public string idGer { get; set; }
        public string mdpGer { get; set; }
    }
}
