//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAtelier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesure
    {
        public int idPers { get; set; }
        public Nullable<int> taille { get; set; }
        public Nullable<int> stature { get; set; }
        public Nullable<int> tour_poitrine { get; set; }
        public Nullable<int> tour_taille { get; set; }
        public Nullable<int> tour_hanche { get; set; }
        public Nullable<int> long_manche { get; set; }
        public Nullable<int> tour_cou { get; set; }
        public Nullable<int> long_pant { get; set; }
        public Nullable<int> long_dev { get; set; }
        public Nullable<int> tour_bras { get; set; }
        public Nullable<int> hauteur_poitrine { get; set; }
    }
}
